client: add support dark colors via settings file (dark_mode variable)
Nukesor/pueue pull request #178
Opened 2021-02-06 11:30 UTC by Mephistophiles

This commit adds the ability to choose  dark colors instead of regular colors . It may
was  useful  for solarized-like themes (green seems weird). By default
the client is using dark_mode = false.

Closes #171

2021-02-06 11:32 UTC, Mephistophiles commented
After review I will create the PR to pueue-lib

2021-02-07 01:19 UTC, Nukesor requested changes
Nice!

Code looks good and clean.
One little nitpick, otherwise this looks good to me.

Feel free to open that PR for `pueue-lib`.
I'll then release a new patch version for this change, so you can properly set the dependency in this PR.

2021-02-07 01:19 UTC, Nukesor commented on client/display/colors.rs
> +pub struct Colors {
A few lines of comments what this class is for would be awesome.

2021-02-08 22:58 UTC, Nukesor requested changes
Oh, two more things.

1. Could you already go ahead and pin the `pueue-lib` version to `0.12.1`?
That way there's no way to get some non-compiling version as soon as 0.12.1 is released.

2. You should add that change to the changelog! Don't forget to mention yourself and to link your Github profile :)

2021-02-09 06:37 UTC, Mephistophiles commented
> Could you already go ahead and pin the pueue-lib version to 0.12.1?
That way there's no way to get some non-compiling version as soon as 0.12.1 is released.

Fixed, I will update Cargo.lock file after pueue-lib is released.

> You should add that change to the changelog! Don't forget to mention yourself and to link your Github profile :)

Should I add the changelog notes to the  `0.12.0` release cycle?

2021-02-09 17:55 UTC, Nukesor commented
1. Ah, of course. I completely forgot about the Cargo.lock :D
Pueue-lib v0.12.1 is released, you should now be able to properly lock the version. Sorry for any inconveniences.

2. Jep, the v0.12 release cycle is the correct place.
I'm planning to release v0.12 in the next few days :)

2021-02-09 19:08 UTC, Mephistophiles commented
Cargo.lock and Changelog have been updated Thanks for your review ! :)

2021-02-09 19:43 UTC, merged

2021-02-09 19:43 UTC, Nukesor commented
Perfect! Code looks good to me.

Thanks for tackling this issue, much appreciated!