Windows support
Nukesor/pueue pull request #183
Opened 2021-03-03 14:58 UTC by oiatz

- Pausing/resuming commands works for now.
- Always sending signals to processes' children.
- Get all processes before `kill` command, so we can ensure that there aren't dangling processes on `kill`

2021-03-03 16:59 UTC, Nukesor reviewed
Hi!
Thanks for taking the time to tackle this issue :+1: 

I'll try to review this in the next few days. It'll probably take a little while, though.
This whole issue requires some research and reading on my end :)

2021-03-06 13:21 UTC, Nukesor requested changes
Thanks again for tackling this issue.
Most comments regard documentation, but there are also a few open questions on how Window's process/thread signaling works.

It would also be awesome, if you could update the Readme:
```
Works on Linux and **partially** on MacOS and Windows. \
```
to something like:
```
- Linux is fully supported and battle-tested.
- Windows has all features, but process handling is **experimental**.
- MacOS only has **rudimentary** process handling (A few things don't work).
    It's still usable, though.
```

Also, don't forget to add your change to the `CHANGELOG.md`, reference your Github profile and link the issue (https://github.com/Nukesor/pueue/issues/114).
I just added the next version to the `CHANGELOG.md` on master. Just rebase/merge and you should be good to go :)

2021-03-16 18:55 UTC, oiatz commented on daemon/platform/windows/process_helper.rs
>      _children: bool,
AFAIK, Windows doesn't provide SIGSTOP or SIGCONT signals [link](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/signal?view=msvc-160)。

So we have to enumerate the set of processes and threads, then call `SuspendThread` or `ResumeThread` to achieve the same effect. But this operation may carry some risk. For example, while enumerating the set of threads, new threads can be created and destroyed. I thought it's at user's risk.

2021-03-26 13:54 UTC, Nukesor approved these changes

2021-03-26 13:55 UTC, Nukesor commented
Changes look good to me :)!

There's a tiny conflict in the changelog. As soon as this is resolved, I'll go ahead and merge the PR.
Thanks again for implementing this,

Cheers!

2021-03-26 17:40 UTC, merged