Refactor: Use From / Into to abstract message sending
Nukesor/pueue pull request #381
Opened 2022-10-19 22:11 UTC by mjpieters

This makes Message use simpler, getting rid of a lot of boilerplate. The task manager channel is now a wrapper type accepting Into<Message>, keeping implementation details closer to the rest of the task manager code base.

## Checklist

- [x] I picked the correct source and target branch.
- [ ] I included a new entry to the `CHANGELOG.md`.
- [x] I checked `cargo clippy` and `cargo fmt`. The CI will fail otherwise anyway.
- [ ] (If applicable) I added tests for this feature or adjusted existing tests.
- [ ] (If applicable) I checked if anything in the wiki needs to be changed.

No changelog entry as this is a code refactor with no functionality difference.

2022-10-20 10:02 UTC, mjpieters commented
I'm not 100% certain how codecov will rate the patch diff hit with #382 applied.

None of the changes here should really affect overall coverage that much since the compiler output for the changes is exactly the same, really.

Only the fact that the same outcome is achieved with fewer lines of code makes a difference, which is why the overall coverage percentage has gone _up_. The patch coverage is down because some of the new `From` implementations are for Message enum values that are currently not covered by tests that would otherwise trigger an `Into<Message>` context, and so those count against the patch coverage count (e.g. `SwitchMessage`, `SendMessage`, `ParallelMessage`, total 9 missed lines, combining source lines accounts for the difference of 3 missed lines).

However, I have no idea how `target: auto` / `threshold: 2%` will be interpreted by codecov when applied to this PR.

2022-10-28 12:01 UTC, Nukesor requested changes
Nice!

This definitely makes the message handling a lot more convenient :)
Thanks!

2022-10-28 13:43 UTC, mjpieters commented on lib/src/network/message.rs
> +
I like! I'll update the PR.

2022-10-28 13:51 UTC, mjpieters commented on daemon/task_handler/mod.rs
> +    pub sender: TaskSender,
Fair enough. I'll revert the change.

My thinking was that the sender is useless without a task handler, so tying its lifetime to the task handler makes sure you have it around and available, but I don't feel strongly about this.

2022-10-28 15:29 UTC, Nukesor approved these changes
Nice. Changes look good to me :)

2022-10-28 15:30 UTC, merged