Support editing task priorities
Nukesor/pueue pull request #490
Opened 2024-01-11 17:15 UTC by jch-13

Adds support for the modification of task priorities in a queue via `pueue edit --priority/-o` and `pueue restart --edit-priority/-o` (fixes #449). Despite the interesting discussion in #449 about how to improve task editing in general, this takes the easy way out and tries to integrate with the existing editing system by using (multiple) editor instances for now. 

## Checklist

- [x] I picked the correct source and target branch.
- [x] I included a new entry to the `CHANGELOG.md`.
- [x] I checked `cargo clippy` and `cargo fmt`. The CI will fail otherwise anyway.
- [x] (If applicable) I added tests for this feature or adjusted existing tests.
- [x] (If applicable) I checked if anything in the wiki needs to be changed.

2024-01-11 18:16 UTC, Nukesor requested changes
Thanks for the PR :) 

It looks pretty clean, two minor nitpicks. I kind of let the feature stall since I wanted to fix this in a proper way, but I guess you're right. This is an good intermediate solution until there's a conclusion on how to move forward.

2024-01-11 18:16 UTC, Nukesor commented on CHANGELOG.md
> +- Support modification of task priorities via `pueue edit --priority/-o` and `pueue restart --edit-priority/-o` [#449](https://github.com/Nukesor/pueue/issues/449)
Minor merge conflict.

I forgot to update the development branch after the latest patch releases on master again. It's an easy fix though :)

2024-01-11 18:16 UTC, Nukesor commented on pueue/tests/client/integration/edit.rs
> +    // Make sure that the label has indeed be deleted
```suggestion
    // Make sure that the priority has indeed been updated.
```

2024-01-11 18:34 UTC, jch-13 commented
Thank you! :)

2024-01-15 13:16 UTC, merged

2024-01-15 13:16 UTC, Nukesor commented
Thanks :)